### PR TITLE
Update for vim.diagnostic

### PR DESCRIPTION
**Pull request by mattleong**
Updates `providers/diagnostics.lua` with updated `vim.diagnostic` api to get diagnostic counts.

### CODE REVIEW

**Comment by mattleong** [comment]
Let me know if you need anything from me to get this merged!

**Review by mrdgo — CHANGES_REQUESTED** [review]
I would prefer [this](https://github.com/glepnir/galaxyline.nvim/pull/219/files) implementation.
Seems more straighforward to me.

Edit: updating the README.md to require nvim 0.6 also seems very important to me.

**Comment by mattleong** [comment]
Tbh I like that one better too. Feel free to close :)

**Comment by mrdgo** [comment]
The reference I posted was a PR to the original repo by glepnir.
IMO you could also adjust your implementation to match the linked one.

At least, I don't know whether you can apply a PR from a different repo.
It might be enough to refer to [dsych](https://github.com/dsych) in the commit message.

**Comment by mattleong** [comment]
Ah gotcha. I was on mobile but I see that now. 

I can update the PR and leave a comment.

**Comment by mattleong** [comment]
@mrdgo PR updated 👍

**Review by NTBBloodbath — APPROVED** [review]

**Comment by NTBBloodbath** [comment]
Hey, I'm really sorry for the HUGE delay on my response. Work and other projects have been taking my whole time lately!

Thank you so much for doing this, I really appreciate the PR changes and will merge this asap. Sorry for the wait! :)

**Comment by NTBBloodbath** [comment]
> updating the README.md to require nvim 0.6 also seems very important to me.

Agreed, if you can please change this before merging I'll be very thankful :)

**Comment by mattleong** [comment]
> Agreed, if you can please change this before merging I'll be very thankful :)

Done! 😄

**Comment by NTBBloodbath** [comment]
Great, thank you so much! :)

**Pull request merged**
